### ISSUE TITLE
mod_case fails to handle multi-directory case-insensitive path matching

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_case#5]
The `mod_case` module currently does case-insensitive matching for the target file in the path, the last component.  However, it _fails_ if the path contains components which themselves require case-insensitive matching.

Consider a path like `/path/To/Some/FileBearing/Directory/File.txt`.  Given a download command like so:
```
RETR /path/To/Some/FileBearing/Directory/file.txt
```
the `mod_case` module can properly match "File.txt" with "file.txt".

However, given this command to download that same file:
```
RETR /path/to/some/filebearing/directory/file.txt
```
the `mod_case` module fails, because it does not perform case-insensitive matching the full path.

The scope of this issue is to rework the `mod_case` internals, so that it will properly handle both of the commands above, as expected.

**Comment by mdell-seradex** [comment]
Note that with my first attempt at this, if the command was issued as `RETR /path/to/some/FileBearing/directory/file.txt` then it would incorrectly exit out as if the case did not need correcting because one of the directories in the path is an exact match (in this case `FileBearing`).

**Comment by Castaglia** [comment]
Now fixed in master.

**Comment by mdell-seradex** [comment]
@Castaglia, I just thought I should mention that I have tested your changes and they work well for my needs.
I hope my repro was helpful to you in some way. :)
